### ISSUE TITLE
ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 8889)

### ISSUE THREAD

**Issue by SevenTailCat** [liyongshen/bili_danmu#1]
您好，我在运行此代码时，出现了以下错误：
`ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 8889)`
经过google等查找，我并没有有找到此错误的解决方法。
您能帮助我吗？
以下是完整报错：
`
/anaconda3/envs/kp/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Task exception was never retrieved
future: <Task finished coro=<bili_live_danmu() done, defined at /Users/seventailcat/PycharmProjects/kp/data/get_video.py:47> exception=ClientProxyConnectionError(61, "Connect call failed ('127.0.0.1', 8889)")>
Traceback (most recent call last):
  File "/anaconda3/envs/kp/lib/python3.7/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/anaconda3/envs/kp/lib/python3.7/asyncio/base_events.py", line 943, in create_connection
    raise exceptions[0]
  File "/anaconda3/envs/kp/lib/python3.7/asyncio/base_events.py", line 930, in create_connection
    await self.sock_connect(sock, address)
  File "/anaconda3/envs/kp/lib/python3.7/asyncio/selector_events.py", line 475, in sock_connect
    return await fut
  File "/anaconda3/envs/kp/lib/python3.7/asyncio/selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 8889)
`

**Comment by liyongshen** [comment]
代理而已，删了proxy就好

**Comment by SevenTailCat** [comment]
谢谢啦～我弄懂啦～！
